version: '3.8'

services:
  odoo-db:
    image: postgres:15
    container_name: odoo-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - odoo-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - odoo-net

  odoo-nginx:
    image: nginx:latest
    container_name: odoo-nginx
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - odoo-net
volumes:
  odoo-db:

networks:
  odoo-net:
    driver: bridge
